/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/About': RouteRecordInfo<'/About', '/About', Record<never, never>, Record<never, never>>,
    '/blog/check': RouteRecordInfo<'/blog/check', '/blog/check', Record<never, never>, Record<never, never>>,
    '/Blog': RouteRecordInfo<'/Blog', '/Blog', Record<never, never>, Record<never, never>>,
    '/Error404': RouteRecordInfo<'/Error404', '/Error404', Record<never, never>, Record<never, never>>,
    '/Experience': RouteRecordInfo<'/Experience', '/Experience', Record<never, never>, Record<never, never>>,
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>>,
    '/MarkdownPlayground': RouteRecordInfo<'/MarkdownPlayground', '/MarkdownPlayground', Record<never, never>, Record<never, never>>,
    '/Playground': RouteRecordInfo<'/Playground', '/Playground', Record<never, never>, Record<never, never>>,
    '/Projects': RouteRecordInfo<'/Projects', '/Projects', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/About.vue': {
      routes: '/About'
      views: never
    }
    'src/pages/blog/check.md': {
      routes: '/blog/check'
      views: never
    }
    'src/pages/Blog.vue': {
      routes: '/Blog'
      views: never
    }
    'src/pages/Error404.vue': {
      routes: '/Error404'
      views: never
    }
    'src/pages/Experience.vue': {
      routes: '/Experience'
      views: never
    }
    'src/pages/Home.vue': {
      routes: '/Home'
      views: never
    }
    'src/pages/MarkdownPlayground.md': {
      routes: '/MarkdownPlayground'
      views: never
    }
    'src/pages/Playground.vue': {
      routes: '/Playground'
      views: never
    }
    'src/pages/Projects.vue': {
      routes: '/Projects'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
